apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-nimbus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poll-nimbus
  template:
    metadata:
      labels:
        app: poll-nimbus
    spec:
      containers:
      - name: poll-nimbus
        image: poll-nimbus:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000